### ISSUE TITLE
ENH: add photonizing code for droplet algorithms

### ISSUE THREAD

**Issue by silkenelson** [slac-lcls/smalldata_tools#6]
Implement a 2-level approach: one 'seeding/finding' step and a second step with fitting. This code should be added to the droplet code as that algorithm is the initial spit in this procedure.

**Comment by vespos** [comment]
Implemented Yanwen's droplet, is that enough to close this issue?

**Comment by silkenelson** [comment]
After having learned what greedy guess is, not really.

**Comment by vespos** [comment]
I know that she has a least-square optimization she can run after the gg algo. I can see to add it as an option to that code. It has been shown that this does not really lead to better photon positioning though (at least for contrast measurments)

**Comment by silkenelson** [comment]
It's less the fitting part than the fact that I think I remember that I did not think her approach would work for more smeared out photons like we'd see on the AndOR for SXR where photons typically have 4 pixels contributing. I may mis-remember the code.

**Comment by silkenelson** [comment]
I've decided that when integrating the greedy-guess photonizing, this is close enough. I'll open a different issue to deal with more smeared out photons.
